version: '3'
services:
  db:
    image: couchdb
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100:9100"
    environment:
      - COUCHDB_USER=rob
      - COUCHDB_PASSWORD=123456
  db_init:
    build: ./db-init
    environment:
      - COUCHDB_USER=rob
      - COUCHDB_PASSWORD=123456
      - COUCHDB_DBNAME=users
      - COUCHDB_HOSTNAME=db
    links:
      - db
  pip:
    build: ./sample-pip
    restart: on-failure
    depends_on:
      - db_init
    links:
      - db
    ports:
      - "4000:3000"
    environment:
      - PGHOST=postgres
      - DB_HOST=db
      - SESSION_SECRET=trench
      - APP_ENV=public
  client:
    build: ./sample-client
    restart: on-failure
    depends_on:
      - pip
    ports:
      - "4001:3000"
    environment:
      - SESSION_SECRET=trench
      - APP_ENV=public
